rotor:
  port: "/dev/ttyUSB0"
  baudrate: 115200
  pulses_per_degree: 10
  az_min: 0
  az_max: 360
  el_min: 0
  el_max: 360

telescope:
  longitude: 12.556680
  latitude: 55.701227
  height: 100
  pressure: null
  temperature: null
  humidity: null
  wavelength: 21.106
  min_el: 0
  max_el: 90